/* =====================================================================
 *
 * Copyright (c) Atos Origin INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 23 17:51:54 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.aof.model.admin;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * A class that represents a row in the t_tra_grp_det table. You can customize
 * the behavior of this class by editing the class, {@link TravelGroupDetail()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTravelGroupDetail implements Serializable {
    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    private ExpenseSubCategory expenseSubCategory;

    private TravelGroup travelGroup;

    /** The value of the simple amountLimit property. */
    private BigDecimal amountLimit;

    private BigDecimal abroadAmountLimit;

    /**
     * Simple constructor of AbstractTravelGroupDetail instances.
     */
    public AbstractTravelGroupDetail() {
    }

    /**
     * Constructor of AbstractTravelGroupDetail instances given a composite primary
     * key.
     * 
     * @param id
     */
    public AbstractTravelGroupDetail(ExpenseSubCategory expenseSubCategory, TravelGroup travelGroup) {
        this.setExpenseSubCategory(expenseSubCategory);
        this.setTravelGroup(travelGroup);
    }

    /**
     * @return Returns the expenseSubCategory.
     */
    public ExpenseSubCategory getExpenseSubCategory() {
        return expenseSubCategory;
    }

    /**
     * @param expenseSubCategory
     *            The expenseSubCategory to set.
     */
    public void setExpenseSubCategory(ExpenseSubCategory expenseSubCategory) {
        this.hashValue = 0;
        this.expenseSubCategory = expenseSubCategory;
    }

    /**
     * @return Returns the travelGroup.
     */
    public TravelGroup getTravelGroup() {
        return travelGroup;
    }

    /**
     * @param travelGroup
     *            The travelGroup to set.
     */
    public void setTravelGroup(TravelGroup travelGroup) {
        this.hashValue = 0;
        this.travelGroup = travelGroup;
    }

    /**
     * Return the value of the amount_limit column.
     * 
     * @return BigDecimal
     */
    public BigDecimal getAmountLimit() {
        return this.amountLimit;
    }

    /**
     * Set the value of the amount_limit column.
     * 
     * @param amountLimit
     */
    public void setAmountLimit(BigDecimal amountLimit) {
        this.amountLimit = amountLimit;
    }

    public BigDecimal getAbroadAmountLimit() {
        return abroadAmountLimit;
    }

    public void setAbroadAmountLimit(BigDecimal abroadAmountLimit) {
        this.abroadAmountLimit = abroadAmountLimit;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (this == rhs)
            return true;
        if (!(rhs instanceof TravelGroupDetail))
            return false;
        TravelGroupDetail that = (TravelGroupDetail) rhs;
        if (this.getExpenseSubCategory() == null || that.getExpenseSubCategory() == null) {
            return false;
        }
        if (!this.getExpenseSubCategory().equals(that.getExpenseSubCategory())) {
            return false;
        }
        if (this.getTravelGroup() == null || that.getTravelGroup() == null) {
            return false;
        }
        if (!this.getTravelGroup().equals(that.getTravelGroup())) {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int tExpSubcateValue = this.getExpenseSubCategory() == null ? 0 : this.getExpenseSubCategory().hashCode();
            result = result * 37 + tExpSubcateValue;
            int tTraGrpValue = this.getTravelGroup() == null ? 0 : this.getTravelGroup().hashCode();
            result = result * 37 + tTraGrpValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

}
