/* =====================================================================
 *
 * Copyright (c) Atos Origin INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 23 17:32:45 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.aof.model.admin;

import java.io.Serializable;

/**
 * A class that represents a row in the t_role_function table. 
 * You can customize the behavior of this class by editing the class, {@link TRoleFunction()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractRoleFunction 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    private Function function;

    private Role role;

    	
    /**
	 * @return Returns the function.
	 */
	public Function getFunction() {
		return function;
	}

	/**
	 * @param function The function to set.
	 */
	public void setFunction(Function function) {
		this.function = function;
	}

	/**
	 * @return Returns the role.
	 */
	public Role getRole() {
		return role;
	}

	/**
	 * @param role The role to set.
	 */
	public void setRole(Role role) {
		this.role = role;
	}

	/**
     * Simple constructor of AbstractTRoleFunction instances.
     */
    public AbstractRoleFunction()
    {
    }

    /**
     * Constructor of AbstractTRoleFunction instances given a composite primary key.
     * @param id
     */
    public AbstractRoleFunction(Function function,Role role)
    {
        this.setFunction(function);
        this.setRole(role);
    }


    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (this == rhs) return true;
        if (! (rhs instanceof RoleFunction))
            return false;
        RoleFunction that = (RoleFunction) rhs;
        if (this.getFunction() == null || that.getFunction() == null)
        {
            return false;
        }
        if (! this.getFunction().equals(that.getFunction()))
        {
            return false;
        }
        if (this.getRole() == null || that.getRole() == null)
        {
            return false;
        }
        if (! this.getRole().equals(that.getRole()))
        {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
        	int result = 17;
            int tFunctionValue = this.getFunction() == null ? 0 : this.getFunction().hashCode();
            result = result * 37 + tFunctionValue;
            int tRoleValue = this.getRole() == null ? 0 : this.getRole().hashCode();
            result = result * 37 + tRoleValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
