/* =====================================================================
 *
 * Copyright (c) Atos Origin INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Jun 14 10:11:27 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.aof.model.admin;

import java.io.Serializable;

/**
 * A class that represents a row in the metadata_det table. 
 * You can customize the behavior of this class by editing the class, {@link Metadata()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 * @author ych
 * @version 1.0 (Nov 10, 2005)
 */
public abstract class AbstractMetadataDetail implements Serializable {
    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    /** The value of the id component of this composite id. */
    private Integer id;

    /** The value of the meta_id component of this composite id. */
    private Metadata type;

    /** The value of the simple engDescription property. */
    private String engDescription;

    /** The value of the simple chnDescription property. */
    private String chnDescription;

    /** The value of the simple engShortDescription property. */
    private String engShortDescription;

    /** The value of the simple chnShortDescription property. */
    private String chnShortDescription;

    /** The value of the simple color property. */
    private String color;

    /**
     * Simple constructor of AbstractMetadataDetail instances.
     */
    public AbstractMetadataDetail() {
    }

    /**
     * Constructor of AbstractUserAuth instances given a composite primary key.
     * 
     * @param id
     * @param type
     */
    public AbstractMetadataDetail(Integer id, Metadata type) {
        this.setId(id);
        this.setType(type);
    }

    /**
     * Return the value of the id column.
     * 
     * @return Integer
     */
    public java.lang.Integer getId() {
        return id;
    }

    /**
     * Set the value of the id column.
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the meta_id column.
     * 
     * @return Metadata
     */
    public Metadata getType() {
        return this.type;
    }

    /**
     * Set the value of the meta_id column.
     * 
     * @param type
     */
    public void setType(Metadata type) {
        this.hashValue = 0;
        this.type = type;
    }

    /**
     * Return the value of the full_description_eng column.
     * 
     * @return String
     */
    public String getEngDescription() {
        return this.engDescription;
    }

    /**
     * Set the value of the full_description_eng column.
     * 
     * @param engDescription
     */
    public void setEngDescription(String engDescription) {
        this.engDescription = engDescription;
    }

    /**
     * Return the value of the full_description_chn column.
     * 
     * @return String
     */
    public String getChnDescription() {
        return this.chnDescription;
    }

    /**
     * Set the value of the full_description_chn column.
     * 
     * @param chnDescription
     */
    public void setChnDescription(String chnDescription) {
        this.chnDescription = chnDescription;
    }

    /**
     * Return the value of the short_description_eng column.
     * 
     * @return String
     */
    public String getEngShortDescription() {
        return this.engShortDescription;
    }

    /**
     * Set the value of the short_description_eng column.
     * 
     * @param engShortDescription
     */
    public void setEngShortDescription(String engShortDescription) {
        this.engShortDescription = engShortDescription;
    }

    /**
     * Return the value of the short_description_chn column.
     * 
     * @return String
     */
    public String getChnShortDescription() {
        return this.chnShortDescription;
    }

    /**
     * Set the value of the short_description_chn column.
     * 
     * @param chnShortDescription
     */
    public void setChnShortDescription(String chnShortDescription) {
        this.chnShortDescription = chnShortDescription;
    }

    /**
     * Return the value of the color column.
     * 
     * @return String
     */
    public String getColor() {
        return this.color;
    }

    /**
     * Set the value of the color column.
     * 
     * @param color
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null) return false;
        if (this == rhs) return true;
        if (!(rhs instanceof MetadataDetail)) return false;
        MetadataDetail that = (MetadataDetail) rhs;
        if (this.getId() != null) {
            if (!this.getId().equals(that.getId())) return false;
        } else {
            if (that.getId() != null) return false;
        }
        if (this.getType() != null) {
            if (!this.getType().equals(that.getType())) return false;
        } else {
            if (that.getType() != null) return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            result = result * 37 + (this.getId() == null ? 0 : this.getId().hashCode());
            result = result * 37 + (this.getType() == null ? 0 : this.getType().hashCode());
            this.hashValue = result;
        }
        return this.hashValue;
    }
}