/* =====================================================================
 *
 * Copyright (c) Atos Origin INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Sep 22 17:05:58 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.aof.model.admin;

import java.io.Serializable;

/**
 * A class that represents a row in the menu table. You can customize the
 * behavior of this class by editing the class, {@link Menu()}. WARNING: DO
 * NOT EDIT THIS FILE. This is a generated file that is synchronized by
 * MyEclipse Hibernate tool integration.
 */
public abstract class AbstractMenu implements Serializable {
    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    /** The simple primary key value. */
    private Integer id;

    /** The value of the function association. */
    private Function function;

    /** The value of the simple name property. */
    private String name;

    /** The value of the simple description property. */
    private String description;

    /** The value of the simple secondName property. */
    private String secondName;

    /** The value of the simple dsecondDescription property. */
    private String secondDescription;

    /** The value of the simple url property. */
    private String url;

    private Menu parentMenu;

    /** The value of the simple onclick property. */
    private String onClick;

    /** The value of the simple onmouseOver property. */
    private String onmouseOver;

    /** The value of the simple onmouseDown property. */
    private String onmouseDown;

    /**
     * Simple constructor of AbstractMenu instances.
     */
    public AbstractMenu() {
    }

    /**
     * Constructor of AbstractMenu instances given a simple primary key.
     * 
     * @param menuId
     */
    public AbstractMenu(Integer menuId) {
        this.setId(menuId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * 
     * @return Integer
     */
    public Integer getId() {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the menu_name column.
     * 
     * @return String
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the value of the menu_name column.
     * 
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Return the value of the sec_menu_nm column.
     * 
     * @return String
     */
    public String getSecondName() {
        return this.secondName;
    }

    /**
     * Set the value of the sec_menu_nm column.
     * 
     * @param secondName
     */
    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }

    public Menu getParentMenu() {
        return parentMenu;
    }

    public void setParentMenu(Menu parentMenu) {
        this.parentMenu = parentMenu;
    }

    /**
     * Return the value of the description column.
     * 
     * @return String
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Set the value of the description column.
     * 
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Return the value of the sec_menu_desc column.
     * 
     * @return String
     */
    public String getSecondDescription() {
        return this.secondDescription;
    }

    /**
     * Set the value of the sec_menu_desc column.
     * 
     * @param secondDescription
     */
    public void setSecondDescription(String secondDescription) {
        this.secondDescription = secondDescription;
    }

    /**
     * Return the value of the function_id column.
     * 
     * @return Function
     */
    public Function getFunction() {
        return this.function;
    }

    /**
     * Set the value of the function_id column.
     * 
     * @param function
     */
    public void setFunction(Function function) {
        this.function = function;
    }

    /**
     * Return the value of the url column.
     * 
     * @return String
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Set the value of the url column.
     * 
     * @param url
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Return the value of the onclick column.
     * 
     * @return String
     */
    public String getOnClick() {
        return this.onClick;
    }

    /**
     * Set the value of the onclick column.
     * 
     * @param onclick
     */
    public void setOnClick(String onClick) {
        this.onClick = onClick;
    }

    /**
     * Return the value of the onmouse_over column.
     * 
     * @return String
     */
    public String getOnmouseOver() {
        return this.onmouseOver;
    }

    /**
     * Set the value of the onmouse_over column.
     * 
     * @param onmouseOver
     */
    public void setOnmouseOver(String onmouseOver) {
        this.onmouseOver = onmouseOver;
    }

    /**
     * Return the value of the onmouse_down column.
     * 
     * @return String
     */
    public String getOnmouseDown() {
        return this.onmouseDown;
    }

    /**
     * Set the value of the onmouse_down column.
     * 
     * @param onmouseDown
     */
    public void setOnmouseDown(String onmouseDown) {
        this.onmouseDown = onmouseDown;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (this == rhs)
            return true;
        if (!(rhs instanceof Menu))
            return false;
        Menu that = (Menu) rhs;
        if (this.getId() != null)
            return this.getId().equals(that.getId());
        return that.getId() == null;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int menuIdValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + menuIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
