/* =====================================================================
 *
 * Copyright (c) Atos Origin INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Oct 11 15:04:41 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.aof.model.admin;

import com.aof.model.metadata.SiteMailReminderType;

import java.io.Serializable;

/**
 * A class that represents a row in the t_site_mail_rem table. You can
 * customize the behavior of this class by editing the class,
 * {@link SiteMailReminder()}. WARNING: DO NOT EDIT THIS FILE. This is a
 * generated file that is synchronized by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSiteMailReminder implements Serializable {

    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    /** identifier field */
    private Site site;

    /** identifier field */
    private SiteMailReminderType type;

    /** persistent field */
    private int dueDay;

    /** persistent field */
    private int intervalDay;

    /** persistent field */
    private int maxTime;

    /**
     * Simple constructor of AbstractSiteMailReminder instances.
     */
    public AbstractSiteMailReminder() {
    }

    /**
     * Constructor of AbstractSiteMailReminder instances given a composite primary key.
     * 
     * @param site
     * @param type
     */
    public AbstractSiteMailReminder(Site site, SiteMailReminderType type) {
        this.site = site;
        this.type = type;
    }

    public SiteMailReminderType getType() {
        return this.type;
    }

    public void setType(SiteMailReminderType type) {
        this.hashValue = 0;
        this.type = type;
    }

    public int getDueDay() {
        return this.dueDay;
    }

    public void setDueDay(int dueDay) {
        this.dueDay = dueDay;
    }

    public int getIntervalDay() {
        return this.intervalDay;
    }

    public void setIntervalDay(int intervalDay) {
        this.intervalDay = intervalDay;
    }

    public int getMaxTime() {
        return this.maxTime;
    }

    public void setMaxTime(int maxTime) {
        this.maxTime = maxTime;
    }

    public Site getSite() {
        return this.site;
    }

    public void setSite(Site site) {
        this.hashValue = 0;
        this.site = site;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null) return false;
        if (this == rhs) return true;
        if (!(rhs instanceof SiteMailReminder)) return false;
        SiteMailReminder that = (SiteMailReminder) rhs;
        if (this.getSite() == null || that.getSite() == null) {
            return false;
        }
        if (!this.getType().equals(that.getType())) {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int tSiteValue = this.getSite() == null ? 0 : this.getSite().hashCode();
            result = result * 37 + tSiteValue;
            int tTypeValue = this.getType() == null ? 0 : this.getType().hashCode();
            result = result * 37 + tTypeValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

}
