/* =====================================================================
 *
 * Copyright (c) Sourceforge INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 23 13:45:10 CST 2005 by MyEclipse Hibernate Tool.
 */
package net.sourceforge.model.business;

import java.io.Serializable;
import java.util.Date;

import net.sourceforge.model.admin.User;
import net.sourceforge.model.metadata.ApproveStatus;
import net.sourceforge.model.metadata.YesNo;

/**
 * A class that represents base information of a row in the approver like table.
 * @author ych
 * @version 1.0 (Nov 16, 2005)
 */
public abstract class BaseApproveRequest implements Serializable {

    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    private String approveRequestId;
    private User approver;
    private User actualApprover;
    
    private int seq;

    private ApproveStatus status; 
    private Date approveDate;
    private String comment;
    private YesNo canModify;
    private Date yourTurnDate;
    private Date lastEmailDate;
    private int sentEmailTimes;
    
    
    /**
     * @return Returns the actualApprover.
     */
    public User getActualApprover() {
        return actualApprover;
    }

    /**
     * @param actualApprover The actualApprover to set.
     */
    public void setActualApprover(User actualApprover) {
        this.actualApprover = actualApprover;
    }

    /**
     * Constructor of BaseApproveRequest.
     */
    protected BaseApproveRequest() {
    }

    /**
     * Constructor of BaseApproveRequest.
     * @param id
     * @param approver
     */
    protected BaseApproveRequest(String id, User approver) {
        this.setApproveRequestId(id);
        this.setApprover(approver);
    }

    /**
     * @return Returns the approveRequestId.
     */
    public String getApproveRequestId() {
        return approveRequestId;
    }

    /**
     * @param approveRequestId The approveRequestId to set.
     */
    public void setApproveRequestId(String approveRequestId) {
        this.hashValue = 0;
        this.approveRequestId = approveRequestId;
    }

    /**
     * @return Returns the approveDate.
     */
    public Date getApproveDate() {
        return approveDate;
    }

    /**
     * @param approveDate The approveDate to set.
     */
    public void setApproveDate(Date approveDate) {
        this.approveDate = approveDate;
    }

    /**
     * @return Returns the approver.
     */
    public User getApprover() {
        return approver;
    }

    /**
     * @param approver The approver to set.
     */
    public void setApprover(User approver) {
        this.hashValue = 0;
        this.approver = approver;
    }

    /**
     * @return Returns the canModify.
     */
    public YesNo getCanModify() {
        return canModify;
    }

    /**
     * @param canModify The canModify to set.
     */
    public void setCanModify(YesNo canModify) {
        this.canModify = canModify;
    }

    /**
     * @return Returns the comment.
     */
    public String getComment() {
        return comment;
    }

    /**
     * @param comment The comment to set.
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * @return Returns the seq.
     */
    public int getSeq() {
        return seq;
    }

    /**
     * @param seq The seq to set.
     */
    public void setSeq(int seq) {
        this.seq = seq;
    }

    /**
     * @return Returns the status.
     */
    public ApproveStatus getStatus() {
        return status;
    }

    /**
     * @param status The status to set.
     */
    public void setStatus(ApproveStatus status) {
        this.status = status;
    }

    /**
     * @return Returns the lastEmailDate.
     */
    public Date getLastEmailDate() {
        return lastEmailDate;
    }

    /**
     * @param lastEmailDate The lastEmailDate to set.
     */
    public void setLastEmailDate(Date lastEmailDate) {
        this.lastEmailDate = lastEmailDate;
    }

    /**
     * @return Returns the sentEmailTimes.
     */
    public int getSentEmailTimes() {
        return sentEmailTimes;
    }

    /**
     * @param sentEmailTimes The sentEmailTimes to set.
     */
    public void setSentEmailTimes(int sentEmailTimes) {
        this.sentEmailTimes = sentEmailTimes;
    }

    /**
     * @return Returns the yourTurnDate.
     */
    public Date getYourTurnDate() {
        return yourTurnDate;
    }

    /**
     * @param yourTurnDate The yourTurnDate to set.
     */
    public void setYourTurnDate(Date yourTurnDate) {
        this.yourTurnDate = yourTurnDate;
    }

    /**
     * 不同子类会对应不同的table，所以应该由子类实现自己的equals方法。
     * 
     * @param rhs
     * @return boolean
     */
    public abstract boolean equals(Object rhs);

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int idValue = this.getApproveRequestId() == null ? 0 : this.getApproveRequestId().hashCode();
            result = result * 37 + idValue;
            int approverValue = this.getApprover() == null ? 0 : this.getApprover().hashCode();
            result = result * 37 + approverValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

}
