/* =====================================================================
 *
 * Copyright (c) Sourceforge INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 23 18:13:55 CST 2005 by MyEclipse Hibernate Tool.
 */
package net.sourceforge.model.admin;

import java.io.Serializable;

/**
 * A class that represents a row in the t_user_site table. You can customize the
 * behavior of this class by editing the class, {@link UserSite()}. WARNING: DO
 * NOT EDIT THIS FILE. This is a generated file that is synchronized by
 * MyEclipse Hibernate tool integration.
 */
public abstract class AbstractUserSite implements Serializable {
    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    private Site site;

    private User user;

    /** The value of the tTraGrp association. */
    private TravelGroup travelGroup;

    /**
     * Simple constructor of AbstractUserSite instances.
     */
    public AbstractUserSite() {
    }

    /**
     * Constructor of AbstractUserSite instances given a composite primary key.
     * 
     * @param id
     */
    public AbstractUserSite(User user, Site site) {
        this.setUser(user);
        this.setSite(site);
    }

    /**
     * @return Returns the site.
     */
    public Site getSite() {
        return site;
    }

    /**
     * @param site
     *            The site to set.
     */
    public void setSite(Site site) {
        this.hashValue = 0;
        this.site = site;
    }

    /**
     * @return Returns the travelGroup.
     */
    public TravelGroup getTravelGroup() {
        return travelGroup;
    }

    /**
     * @param travelGroup
     *            The travelGroup to set.
     */
    public void setTravelGroup(TravelGroup travelGroup) {
        this.travelGroup = travelGroup;
    }

    /**
     * @return Returns the user.
     */
    public User getUser() {
        return user;
    }

    /**
     * @param user
     *            The user to set.
     */
    public void setUser(User user) {
        this.hashValue = 0;
        this.user = user;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null)
            return false;
        if (this == rhs)
            return true;
        if (!(rhs instanceof UserSite))
            return false;
        UserSite that = (UserSite) rhs;
        if (this.getSite() == null || that.getSite() == null) {
            return false;
        }
        if (!this.getSite().equals(that.getSite())) {
            return false;
        }
        if (this.getUser() == null || that.getUser() == null) {
            return false;
        }
        if (!this.getUser().equals(that.getUser())) {
            return false;
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int tSiteValue = this.getSite() == null ? 0 : this.getSite().hashCode();
            result = result * 37 + tSiteValue;
            int tUserValue = this.getUser() == null ? 0 : this.getUser().hashCode();
            result = result * 37 + tUserValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
