/* =====================================================================
 *
 * Copyright (c) Sourceforge INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 23 17:51:39 CST 2005 by MyEclipse Hibernate Tool.
 */
package net.sourceforge.model.admin;

import java.io.Serializable;

import net.sourceforge.model.metadata.EnabledDisabled;

/**
 * A class that represents a row in the t_tra_grp table. 
 * You can customize the behavior of this class by editing the class, {@link TTraGrp()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTravelGroup 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the tSite association. */
    private Site site;


    /** The value of the simple name property. */
    private java.lang.String name;

    /** The value of the simple enabled property. */
    private EnabledDisabled enabled;

    /**
     * Simple constructor of AbstractTTraGrp instances.
     */
    public AbstractTravelGroup()
    {
    }

    /**
     * Constructor of AbstractTTraGrp instances given a simple primary key.
     * @param id
     */
    public AbstractTravelGroup(java.lang.Integer id)
    {
    	this.hashValue=0;
        this.setId(id);
    }

    
    
    /**
	 * @return Returns the enabled.
	 */
	public EnabledDisabled getEnabled() {
		return enabled;
	}

	/**
	 * @param enabled The enabled to set.
	 */
	public void setEnabled(EnabledDisabled enabled) {
		this.enabled = enabled;
	}

	/**
	 * @return Returns the id.
	 */
	public java.lang.Integer getId() {
		return id;
	}

	/**
	 * @param id The id to set.
	 */
	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	/**
	 * @return Returns the name.
	 */
	public java.lang.String getName() {
		return name;
	}

	/**
	 * @param name The name to set.
	 */
	public void setName(java.lang.String name) {
		this.name = name;
	}

	/**
	 * @return Returns the site.
	 */
	public Site getSite() {
		return site;
	}

	/**
	 * @param site The site to set.
	 */
	public void setSite(Site site) {
		this.site = site;
	}

	/**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
    	if (rhs == null) return false;
        if (this == rhs) return true;
        if (!(rhs instanceof TravelGroup)) return false;
        TravelGroup that = (TravelGroup) rhs;
        if (this.getId() != null) return this.getId().equals(that.getId());
        return that.getId() == null;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int traGrpIdValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + traGrpIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
