/* =====================================================================
 *
 * Copyright (c) Sourceforge INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 23 15:43:29 CST 2005 by MyEclipse Hibernate Tool.
 */
package net.sourceforge.model.admin;

import java.util.Date;

import net.sourceforge.model.metadata.EnabledDisabled;
import net.sourceforge.model.metadata.SupplierPromoteStatus;
import net.sourceforge.model.metadata.YesNo;
import org.apache.commons.beanutils.PropertyUtils;
/**
 * 代表supplier和supplier_history中共有的字段
 */
public abstract class BaseSupplier {
    /**
     * The cached hash code value for this instance. Settting to 0 triggers
     * re-calculation.
     */
    private int hashValue = 0;

    /** The simple primary key value. */
    private Integer id;

    /** The value of the simple code property. */
    private String code;

    /** The value of the Site association. */
    private Site site;

    /** The value of the tCurrency association. */
    private Currency currency;

    /** The value of the simple supName property. */
    private String name;

    /** The value of the simple address1 property. */
    private String address1;

    /** The value of the simple address2 property. */
    private String address2;

    /** The value of the simple address3 property. */
    private String address3;

    /** The value of the simple city property. */
    private City city;

    /** The value of the simple post property. */
    private String post;

    /** The value of the simple attention1 property. */
    private String attention1;

    /** The value of the simple attention2 property. */
    private String attention2;

    /** The value of the simple tele1 property. */
    private String telephone1;

    /** The value of the simple ext1 property. */
    private String ext1;

    /** The value of the simple tele2 property. */
    private String telephone2;

    /** The value of the simple ext2 property. */
    private String ext2;

    /** The value of the simple fax1 property. */
    private String fax1;

    /** The value of the simple fax2 property. */
    private String fax2;

    /** The value of the simple purAccount property. */
    private String purchaseAccount;

    /** The value of the simple purSubaccount property. */
    private String purchaseSubAccount;

    /** The value of the simple purCostCenter property. */
    private String purchaseCostCenter;

    /** The value of the simple apAccount property. */
    private String apAccount;

    /** The value of the simple apSubaccount property. */
    private String apSubAccount;

    /** The value of the simple apCostCenter property. */
    private String apCostCenter;

    /** The value of the simple bank property. */
    private String bank;

    /** The value of the simple crTerms property. */
    private String creditTerms;

    /** The value of the simple contact property. */
    private String contact;

    /** The value of the simple conStrDate property. */
    private java.util.Date contractStartDate;

    /** The value of the simple conExpDate property. */
    private java.util.Date contractExpireDate;

    /** The value of the simple enabled property. */
    private EnabledDisabled enabled;

    private YesNo airTicket;

    private SupplierPromoteStatus promoteStatus;

    private Date confirmDate;

    private Date promoteDate;
    
    private Country country;
    
    /**
     * Simple constructor of BaseSupplier instances.
     */
    public BaseSupplier() {
    }

    /**
     * Constructor of BaseSupplier instances given a simple primary key.
     * 
     * @param id
     */
    public BaseSupplier(Integer id) {
        this.setId(id);
    }

    /**
     * @return Returns the airTicket.
     */
    public YesNo getAirTicket() {
        return airTicket;
    }

    /**
     * @param airTicket
     *            The airTicket to set.
     */
    public void setAirTicket(YesNo airTicket) {
        this.airTicket = airTicket;
    }

    /**
     * @return Returns the promoteStatus.
     */
    public SupplierPromoteStatus getPromoteStatus() {
        return promoteStatus;
    }

    /**
     * @param promoteStatus
     *            The promoteStatus to set.
     */
    public void setPromoteStatus(SupplierPromoteStatus promoteStatus) {
        this.promoteStatus = promoteStatus;
    }

    /**
     * @return Returns the address1.
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * @param address1
     *            The address1 to set.
     */
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * @return Returns the address2.
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * @param address2
     *            The address2 to set.
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * @return Returns the address3.
     */
    public String getAddress3() {
        return address3;
    }

    /**
     * @param address3
     *            The address3 to set.
     */
    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    /**
     * @return Returns the apAccount.
     */
    public String getApAccount() {
        return apAccount;
    }

    /**
     * @param apAccount
     *            The apAccount to set.
     */
    public void setApAccount(String apAccount) {
        this.apAccount = apAccount;
    }

    /**
     * @return Returns the apCostCenter.
     */
    public String getApCostCenter() {
        return apCostCenter;
    }

    /**
     * @param apCostCenter
     *            The apCostCenter to set.
     */
    public void setApCostCenter(String apCostCenter) {
        this.apCostCenter = apCostCenter;
    }

    /**
     * @return Returns the apSubaccount.
     */
    public String getApSubAccount() {
        return apSubAccount;
    }

    /**
     * @param apSubaccount
     *            The apSubaccount to set.
     */
    public void setApSubAccount(String apSubaccount) {
        this.apSubAccount = apSubaccount;
    }

    /**
     * @return Returns the attention1.
     */
    public String getAttention1() {
        return attention1;
    }

    /**
     * @param attention1
     *            The attention1 to set.
     */
    public void setAttention1(String attention1) {
        this.attention1 = attention1;
    }

    /**
     * @return Returns the attention2.
     */
    public String getAttention2() {
        return attention2;
    }

    /**
     * @param attention2
     *            The attention2 to set.
     */
    public void setAttention2(String attention2) {
        this.attention2 = attention2;
    }

    /**
     * @return Returns the bank.
     */
    public String getBank() {
        return bank;
    }

    /**
     * @param bank
     *            The bank to set.
     */
    public void setBank(String bank) {
        this.bank = bank;
    }

    /**
     * @return Returns the city.
     */
    public City getCity() {
        return city;
    }

    /**
     * @param city
     *            The city to set.
     */
    public void setCity(City city) {
        this.city = city;
    }

    /**
     * @return Returns the contact.
     */
    public String getContact() {
        return contact;
    }

    /**
     * @param contact
     *            The contact to set.
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * @return Returns the contractExpireDate.
     */
    public java.util.Date getContractExpireDate() {
        return contractExpireDate;
    }

    /**
     * @param contractExpireDate
     *            The contractExpireDate to set.
     */
    public void setContractExpireDate(java.util.Date contractExpireDate) {
        this.contractExpireDate = contractExpireDate;
    }

    /**
     * @return Returns the contractStartDate.
     */
    public java.util.Date getContractStartDate() {
        return contractStartDate;
    }

    /**
     * @param contractStartDate
     *            The contractStartDate to set.
     */
    public void setContractStartDate(java.util.Date contractStartDate) {
        this.contractStartDate = contractStartDate;
    }

    /**
     * @return Returns the creditTerms.
     */
    public String getCreditTerms() {
        return creditTerms;
    }

    /**
     * @param creditTerms
     *            The creditTerms to set.
     */
    public void setCreditTerms(String creditTerms) {
        this.creditTerms = creditTerms;
    }

    /**
     * @return Returns the currency.
     */
    public Currency getCurrency() {
        return currency;
    }

    /**
     * @param currency
     *            The currency to set.
     */
    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    /**
     * @return Returns the enabled.
     */
    public EnabledDisabled getEnabled() {
        return enabled;
    }

    /**
     * @param enabled
     *            The enabled to set.
     */
    public void setEnabled(EnabledDisabled enabled) {
        this.enabled = enabled;
    }

    /**
     * @return Returns the ext1.
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * @param ext1
     *            The ext1 to set.
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    /**
     * @return Returns the ext2.
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * @param ext2
     *            The ext2 to set.
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }

    /**
     * @return Returns the fax1.
     */
    public String getFax1() {
        return fax1;
    }

    /**
     * @param fax1
     *            The fax1 to set.
     */
    public void setFax1(String fax1) {
        this.fax1 = fax1;
    }

    /**
     * @return Returns the fax2.
     */
    public String getFax2() {
        return fax2;
    }

    /**
     * @param fax2
     *            The fax2 to set.
     */
    public void setFax2(String fax2) {
        this.fax2 = fax2;
    }

    /**
     * @return Returns the id.
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id
     *            The id to set.
     */
    public void setId(Integer id) {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * @return Returns the code.
     */
    public String getCode() {
        return code;
    }

    /**
     * @param code The code to set.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * @return Returns the name.
     */
    public String getName() {
        return name;
    }

    /**
     * @param name
     *            The name to set.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return Returns the post.
     */
    public String getPost() {
        return post;
    }

    /**
     * @param post
     *            The post to set.
     */
    public void setPost(String post) {
        this.post = post;
    }

    /**
     * @return Returns the purchaseAccount.
     */
    public String getPurchaseAccount() {
        return purchaseAccount;
    }

    /**
     * @param purchaseAccount
     *            The purchaseAccount to set.
     */
    public void setPurchaseAccount(String purchaseAccount) {
        this.purchaseAccount = purchaseAccount;
    }

    /**
     * @return Returns the purchaseCostCenter.
     */
    public String getPurchaseCostCenter() {
        return purchaseCostCenter;
    }

    /**
     * @param purchaseCostCenter
     *            The purchaseCostCenter to set.
     */
    public void setPurchaseCostCenter(String purchaseCostCenter) {
        this.purchaseCostCenter = purchaseCostCenter;
    }

    /**
     * @return Returns the purchaseSubAccount.
     */
    public String getPurchaseSubAccount() {
        return purchaseSubAccount;
    }

    /**
     * @param purchaseSubAccount
     *            The purchaseSubAccount to set.
     */
    public void setPurchaseSubAccount(String purchaseSubAccount) {
        this.purchaseSubAccount = purchaseSubAccount;
    }

    /**
     * @return Returns the site.
     */
    public Site getSite() {
        return site;
    }

    /**
     * @param site
     *            The site to set.
     */
    public void setSite(Site site) {
        this.site = site;
    }

    /**
     * @return Returns the telephone1.
     */
    public String getTelephone1() {
        return telephone1;
    }

    /**
     * @param telephone1
     *            The telephone1 to set.
     */
    public void setTelephone1(String telephone1) {
        this.telephone1 = telephone1;
    }

    /**
     * @return Returns the telephone2.
     */
    public String getTelephone2() {
        return telephone2;
    }

    /**
     * @param telephone2
     *            The telephone2 to set.
     */
    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }

    /**
     * @return Returns the confirmDate.
     */
    public Date getConfirmDate() {
        return confirmDate;
    }

    /**
     * @param confirmDate The confirmDate to set.
     */
    public void setConfirmDate(Date confirmDate) {
        this.confirmDate = confirmDate;
    }

    
    /**
	 * @return Returns the promoteDate.
	 */
	public Date getPromoteDate() {
		return promoteDate;
	}

	/**
	 * @param promoteDate The promoteDate to set.
	 */
	public void setPromoteDate(Date promoteDate) {
		this.promoteDate = promoteDate;
	}

	/**
     * Supplier和SupplierHistory需要实现自己的equals方法
     * 
     * @param rhs
     * @return boolean
     */
    public abstract boolean equals(Object rhs);

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern
     * with the exception of array properties (these are very unlikely primary
     * key types).
     * 
     * @return int
     */
    public int hashCode() {
        if (this.hashValue == 0) {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
    
    public void copySupplier(BaseSupplier copySupplier)  {
    	try {
            PropertyUtils.copyProperties(this,copySupplier);
        } catch (Exception e) {
           throw new RuntimeException(e);
        }
    }
    
    public boolean contentEqual(Supplier that)
    {
        if (!this.getId().equals(that.getId())) return false;
        if (this.getSite()!=null) {
        	if (!this.getSite().equals(that.getSite())) return false;
        } else {
        	if (that.getSite()!=null) return false;
        }
        if (this.getName()!=null) {
        	if (!this.getName().equals(that.getName())) return false;
        } else {
        	if (that.getName()!=null) return false;
        }
        if (this.getAddress1()!=null) {
        	if (!this.getAddress1().equals(that.getAddress1())) return false;
        } else {
        	if (that.getAddress1()!=null) return false;
        }
        if (this.getApAccount()!=null) {
        	if (!this.getApAccount().equals(that.getApAccount())) return false;
        } else {
        	if (that.getApAccount()!=null) return false;
        }
        if (this.getApCostCenter()!=null) {
        	if (!this.getApCostCenter().equals(that.getApCostCenter())) return false;
        } else {
        	if (that.getApCostCenter()!=null) return false;
        }
        if (this.getApSubAccount()!=null) {
        	if (!this.getApSubAccount().equals(that.getApSubAccount())) return false;
        } else {
        	if (that.getApSubAccount()!=null) return false;
        }
        if (this.getBank()!=null) {
        	if (!this.getBank().equals(that.getBank())) return false;
        } else {
        	if (that.getBank()!=null) return false;
        }
        if (this.getCity()!=null) {
        	if (!this.getCity().equals(that.getCity())) return false;
        } else {
        	if (that.getCity()!=null) return false;
        }
        if (this.getCountry()!=null) {
            if (!this.getCountry().equals(that.getCountry())) return false;
        } else {
            if (that.getCountry()!=null) return false;
        }
        if (this.getContact()!=null) {
        	if (!this.getContact().equals(that.getContact())) return false;
        } else {
        	if (that.getContact()!=null) return false;
        }
        if (this.getContractExpireDate()!=null) {
        	if (!this.getContractExpireDate().equals(that.getContractExpireDate())) return false;
        } else {
        	if (that.getContractExpireDate()!=null) return false;
        }
        if (this.getContractStartDate()!=null) {
        	if (!this.getContractStartDate().equals(that.getContractStartDate())) return false;
        } else {
        	if (that.getContractStartDate()!=null) return false;
        }
        if (this.getCurrency()!=null) {
        	if (!this.getCurrency().equals(that.getCurrency())) return false;
        } else {
        	if (that.getCurrency()!=null) return false;
        }
        if (this.getTelephone1()!=null) {
        	if (!this.getTelephone1().equals(that.getTelephone1())) return false;
        } else {
        	if (that.getTelephone1()!=null) return false;
        }
        if (this.getFax1()!=null) {
        	if (!this.getFax1().equals(that.getFax1())) return false;
        } else {
        	if (that.getFax1()!=null) return false;
        }
        if (this.getPost()!=null) {
        	if (!this.getPost().equals(that.getPost())) return false;
        } else {
        	if (that.getPost()!=null) return false;
        }
        if (this.getPurchaseAccount()!=null) {
        	if (!this.getPurchaseAccount().equals(that.getPurchaseAccount())) return false;
        } else {
        	if (that.getPurchaseAccount()!=null) return false;
        }
        if (this.getPurchaseCostCenter()!=null) {
        	if (!this.getPurchaseCostCenter().equals(that.getPurchaseCostCenter())) return false;
        } else {
        	if (that.getPurchaseCostCenter()!=null) return false;
        }
        if (this.getPurchaseSubAccount()!=null) {
        	if (!this.getPurchaseSubAccount().equals(that.getPurchaseSubAccount())) return false;
        } else {
        	if (that.getPurchaseSubAccount()!=null) return false;
        }
        if (this.getEnabled()!=null) {
        	if (!this.getEnabled().equals(that.getEnabled())) return false;
        } else {
        	if (that.getEnabled()!=null) return false;
        }
        return true;
    }

    /**
     * @return Returns the country.
     */
    public Country getCountry() {
        return country;
    }

    /**
     * @param country The country to set.
     */
    public void setCountry(Country country) {
        this.country = country;
    }
    
    
}
