/* =====================================================================
 *
 * Copyright (c) Sourceforge INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 23 13:45:10 CST 2005 by MyEclipse Hibernate Tool.
 */
package net.sourceforge.model.business.ta;

import java.util.Date;

import net.sourceforge.model.admin.City;
import net.sourceforge.model.admin.Hotel;
import net.sourceforge.model.admin.Price;
import net.sourceforge.model.metadata.SingleReturn;
import net.sourceforge.model.metadata.TravelApplicationStatus;
import net.sourceforge.model.metadata.TravellingMode;

/**
 * 该class代表t_ta表和t_ta_history表中一行共有的信息.
 */
public abstract class BaseTravelApplication {

    private TravelApplicationStatus status;
    private City fromCity;
    private City toCity;
    private Hotel hotel;
    private String hotelName;
    private Price price;
    private String roomDescription;
    private Date checkInDate;
    private Date checkOutDate;
    private TravellingMode travellingMode;
    private SingleReturn singleOrReturn;
    private Date fromDate;
    private Date fromTime;
    private Date toDate;
    private Date toTime;
    private String approveRequestId;

    /**
     * @return Returns the approveRequestId.
     */
    public String getApproveRequestId() {
        return approveRequestId;
    }
    /**
     * @param approveRequestId The approveRequestId to set.
     */
    public void setApproveRequestId(String approveRequestId) {
        this.approveRequestId = approveRequestId;
    }
    /**
     * @return Returns the checkInDate.
     */
    public Date getCheckInDate() {
        return checkInDate;
    }
    /**
     * @param checkInDate The checkInDate to set.
     */
    public void setCheckInDate(Date checkInDate) {
        this.checkInDate = checkInDate;
    }
    /**
     * @return Returns the checkOutDate.
     */
    public Date getCheckOutDate() {
        return checkOutDate;
    }
    /**
     * @param checkOutDate The checkOutDate to set.
     */
    public void setCheckOutDate(Date checkOutDate) {
        this.checkOutDate = checkOutDate;
    }
    /**
     * @return Returns the fromCity.
     */
    public City getFromCity() {
        return fromCity;
    }
    /**
     * @param fromCity The fromCity to set.
     */
    public void setFromCity(City fromCity) {
        this.fromCity = fromCity;
    }
    /**
     * @return Returns the fromDate.
     */
    public Date getFromDate() {
        return fromDate;
    }
    /**
     * @param fromDate The fromDate to set.
     */
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    /**
     * @return Returns the fromTime.
     */
    public Date getFromTime() {
        return fromTime;
    }
    /**
     * @param fromTime The fromTime to set.
     */
    public void setFromTime(Date fromTime) {
        this.fromTime = fromTime;
    }
    /**
     * @return Returns the hotel.
     */
    public Hotel getHotel() {
        return hotel;
    }
    /**
     * @param hotel The hotel to set.
     */
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    /**
     * @return Returns the hotelName.
     */
    public String getHotelName() {
        return hotelName;
    }
    /**
     * @param hotelName The hotelName to set.
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }
    /**
     * @return Returns the price.
     */
    public Price getPrice() {
        return price;
    }
    /**
     * @param price The price to set.
     */
    public void setPrice(Price price) {
        this.price = price;
    }
    /**
     * @return Returns the roomDescription.
     */
    public String getRoomDescription() {
        return roomDescription;
    }
    /**
     * @param roomDescription The roomDescription to set.
     */
    public void setRoomDescription(String roomDescription) {
        this.roomDescription = roomDescription;
    }
    /**
     * @return Returns the singleOrReturn.
     */
    public SingleReturn getSingleOrReturn() {
        return singleOrReturn;
    }
    /**
     * @param singleOrReturn The singleOrReturn to set.
     */
    public void setSingleOrReturn(SingleReturn singleOrReturn) {
        this.singleOrReturn = singleOrReturn;
    }
    /**
     * @return Returns the status.
     */
    public TravelApplicationStatus getStatus() {
        return status;
    }
    /**
     * @param status The status to set.
     */
    public void setStatus(TravelApplicationStatus status) {
        this.status = status;
    }
    /**
     * @return Returns the toCity.
     */
    public City getToCity() {
        return toCity;
    }
    /**
     * @param toCity The toCity to set.
     */
    public void setToCity(City toCity) {
        this.toCity = toCity;
    }
    /**
     * @return Returns the toDate.
     */
    public Date getToDate() {
        return toDate;
    }
    /**
     * @param toDate The toDate to set.
     */
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    /**
     * @return Returns the toTime.
     */
    public Date getToTime() {
        return toTime;
    }
    /**
     * @param toTime The toTime to set.
     */
    public void setToTime(Date toTime) {
        this.toTime = toTime;
    }
    /**
     * @return Returns the travellingMode.
     */
    public TravellingMode getTravellingMode() {
        return travellingMode;
    }
    /**
     * @param travellingMode The travellingMode to set.
     */
    public void setTravellingMode(TravellingMode travellingMode) {
        this.travellingMode = travellingMode;
    }



}
