/* =====================================================================
 *
 * Copyright (c) Atos Origin INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 23 15:43:29 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.aof.model.admin;

import java.io.Serializable;

/**
 * A class that represents a row in the supplier_history table. You can
 * customize the behavior of this class by editing the class,
 * {@link SupplierHistory()}. WARNING: DO NOT EDIT THIS FILE. This is a
 * generated file that is synchronized by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSupplierHistory extends BaseSupplier implements Serializable {

    /** The one-to-one supplier association. */
    private Supplier supplier;

    /**
     * Simple constructor of AbstractSupplierHistory instances.
     */
    public AbstractSupplierHistory() {
    }

    /**
     * Constructor of AbstractSupplierHistory instances given a simple primary
     * key.
     * 
     * @param supplier
     */
    public AbstractSupplierHistory(Supplier supplier) {
        this.setSupplier(supplier);
    }

    /**
     * Return one-to-one association that identifies this object.
     * 
     * @return Supplier
     */
    public Supplier getSupplier() {
        return supplier;
    }

    /**
     * Set one-to-one association that identifies this object.
     * 
     * @param Supplier
     */
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
        if (supplier == null) {
            this.setId(null);
        } else {
            this.setId(supplier.getId());
        }
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null) return false;
        if (this == rhs) return true;
        if (!(rhs instanceof SupplierHistory)) return false;
        SupplierHistory that = (SupplierHistory) rhs;
        if (this.getId() != null) return this.getId().equals(that.getId());
        return that.getId() == null;
    }

}
