/* =====================================================================
 *
 * Copyright (c) Atos Origin INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 23 14:18:06 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.aof.model.admin;

import java.io.Serializable;

import com.aof.model.BaseAttachmentContent;

/**
 * A class that represents a row (only content field) in the supplier_contract
 * table. You can customize the behavior of this class by editing the class,
 * {@link SupploerContractContent()}. WARNING: DO NOT EDIT THIS FILE. This is a
 * generated file that is synchronized by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSupplierContractContent extends BaseAttachmentContent implements Serializable {

    /**
     * Simple constructor of AbstractSupplierContractContent instances.
     */
    public AbstractSupplierContractContent() {
    }

    /**
     * Constructor of AbstractSupplierContractContent instances given a simple primary
     * key.
     * 
     * @param id
     */
    public AbstractSupplierContractContent(Integer id) {
        this.setId(id);
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the
     * primary key values.
     * 
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs) {
        if (rhs == null) return false;
        if (this == rhs) return true;
        if (!(rhs instanceof SupplierContractContent)) return false;
        SupplierContractContent that = (SupplierContractContent) rhs;
        if (this.getId() != null) return this.getId().equals(that.getId());
        return that.getId() == null;
    }
}
