/* =====================================================================
 *
 * Copyright (c) Atos Origin INFORMATION TECHNOLOGY All rights reserved.
 *
 * =====================================================================
 */

/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Sep 23 13:45:10 CST 2005 by MyEclipse Hibernate Tool.
 */
package com.aof.model.business.po;

import java.math.BigDecimal;

import com.aof.model.metadata.PurchaseOrderStatus;

/**
 * 该class代表t_po表和t_po_his表中一行共有的信息.
 */
public abstract class BasePurchaseOrder {

    private PurchaseOrderStatus status;
    private BigDecimal amount;
    private String approveRequestId;

    /**
     * @return Returns the amount.
     */
    public BigDecimal getAmount() {
        return amount;
    }
    /**
     * @param amount The amount to set.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    /**
     * @return Returns the approveRequestId.
     */
    public String getApproveRequestId() {
        return approveRequestId;
    }
    /**
     * @param approveRequestId The approveRequestId to set.
     */
    public void setApproveRequestId(String approveRequestId) {
        this.approveRequestId = approveRequestId;
    }
    /**
     * @return Returns the status.
     */
    public PurchaseOrderStatus getStatus() {
        return status;
    }
    /**
     * @param status The status to set.
     */
    public void setStatus(PurchaseOrderStatus status) {
        this.status = status;
    }

}
